export const BadgeMessages = {
  BADGE_CREATE_SUCC:"Badge Created",
  CREATE_FAIL:"Failed to create badge.",
  SOMETHING_WENT_WRONG:"Something went wrong.",
  FAIL_TO_DELETE:"Failed to delete badge",
};

export const ResourceAllocationMessages = {
  PROJECT_SELECT_ERR:"Please select a valid project",
  TYPEOFWORK_SELECT_ERR:"Please select a valid type of work",
  TYPEOFWORK_REQ:"Please select type of work",
  USER_REQ:"Please select user",
  TIME_RANGE:"Pick time range",
  DESCRIPTION_REQ:"Please enter a description",
  FAILED_TO_LOAD_DATA:"Failed to load booking data",
  BOOKING_DELETE_SUCC:"Booking deleted successfully",
  BOOKING_UPDATE_SUCC:"Booking updated successfully",
  BOOKING_UPDATE_FAIL:"Failed to update booking",
  VALID_HEX_CODE_REQ:"Please enter a valid hex color code (e.g. #5CDB95)",
  ALL_RESOURCES_ALLOCATED_SUCC:"All resources allocated successfully",
  RESOURCE_ALLOCATE_FAIL:"Failed to allocate one or more resources",
  BOOKING_MOVE_SUCC:"Booking moved successfully",
  BOOKING_MOVE_FAIL:"Failed to move booking",
  BOOKING_DEL_FAIL:"Failed to delete booking",
  BOOKING_COPY_SUCC:"Booking copied successfully",
  BOOKING_COPY_FAIL:"Failed to copy booking",
  BOOKING_TIME_UPDATED_SUCC:"Booking time updated successfully!",
  BOOKING_TIME_UPDATED_FAIL:"Failed to update booking time.",
};

export const AssetMessages = {
  ASSET_TYPE_ADD_SUCC:"Asset Type added successfully!",
  ASSET_TYPE_UPDATE_SUCC:"Asset Type updated successfully!",
  ASSET_TYPE_DEL_SUCC:"Asset type deleted successfully!",
  ASSET_TYPE_DEL_FAIL:"Failed to delete asset type. Please try again.",
  ASSET_TYPENAME_REQ:"Type name is required.",
  CATEGORY_DEL_SUCC:"Category deleted successfully!",
  CATEGORY_DEL_FAIL:"Failed to delete category.",
  CATEGORY_NAME_REQ:"Category name is required!",
  CATEGORY_UPDATE_SUCC:"Category updated successfully!",
  CATEGORY_UPDATE_FAIL:"Failed to update category.",
  CATEGORY_ADD_SUCC:"Asset Category added successfully!",
 };

export const CommonMessages = {
 ERR_MSG:"Error",
 SOMETHING_WENT_WRONG:"Something went wrong",
};

export const CompanyMessages = {
  COMPANY_FETCH_FAIL:"Failed to fetch companies.",
  COMPANY_CREATED_SUCC:"Company created successfully!",
  COMPANY_NAME_REQ:"Company name is required!",
  COMPANY_NAME_ALREADY_EXISTS:"Company name already exists.",
  DOMAIN_NAME_REQ:"Please input the domain!",
 };

export const FeedbackMessages = {
  REVIEW_REQUEST_SUCC:"Review Request Sent",
  SELECTED_USERS_GOT_NOTIFIED:"The selected users have been notified to submit a review.",
  ERROR:"There was an error",
  FEEDBACK_SUBMIT:"Feedback Submitted",
  FEEDBACK_SUBMIT_SUCC:"Your feedback has been submitted successfully.",
  SUBMISSION_FAILED:"Submission Failed",
  ERR_TRY_AGAIN:"There was an error submitting your feedback. Please try again.",
  INTERNAL_NOTE_ADDED:"Internal Note Added."
 };

export const LoginMessages = {
    LOGIN_SUCC: 'Login successful!',
    LOGIN_ERR:'Login failed',
    EMAIL:'Please enter your email!',
    EMAIL_INVALID:'Invalid email format!',
    PASSWORD: 'Please enter your password!',
    UNAUTHORIZED_EMAIL_ERR:"Unauthorized! Your email is not registered.",
    GOOGLE_LOGIN_FAILED:"Google Login Failed!",
  };

  export const RegisterMessages = {
    REGISTER_PASSWORD_REQ:'Password is required',
    REGISTER_PASS_PATTERN:'Must be 8+ chars, 1 uppercase, 1 lowercase, 1 number, 1 special char.',
    RESGISTER_SUCCESS:'User registered successfully!',
    REGISTER_ERR:'Error occurred',
    USERNAME:'Username is required',
    USERNAME_LIMIT:'Username must be at least 3 characters',
    USERNAME_CHECK_ERR:'Error checking username',
    REQ_FIELD:'Required',
    FNAME_LIMIT:'Firstname should be minimum of 3 characters',
    LNAME_LIMIT:'Lastname should be minimum of 3 characters',
    USERNAME_MAX_LIMIT:'Username should not exceed 10 characters',
    USERNAME_PATTERN:'Only letters, numbers, or underscores allowed',
    EMAIL_INVALID:'Invalid Email format',
    CONFIRM_PASSWORD: 'Please confirm your password',
    PASSWORD: 'Please enter your password',
    PASS_MATCH_ERR:'Passwords do not match!',
    EMAIL_CHECK_ERR:"Error checking email",
  };

  export const ResetPasswordMessages = {
    EMAIL_SENT_SUCC:'Password reset link sent to your email!',
    EMAIL_SENT_ERR:'Failed to send reset email. Try again.',
    EMAIL:'Please enter your email!',
    EMAIL_INVALID:'Invalid email format!',
    PASS_MATCH_ERR:'Password do not match!',
    PASS_RESET_SUCC:'Password successfully reset!',
    PASS_RESET_ERR:'Failed to reset password. Try again.',
    PASS_REQ:'Password is required',
    PASS_CONFIRM:'Confirm your password',
    PASS_LIMIT:'Password must be at least 8 characters',
    PASS_PATTERN:'Password must have uppercase, lowercase, and a number',
  };

  export const WorkspaceMessages = {
    WORKSPACENAME_REQ:'Workspacename is required',
    WORKSPACENAME_PATTERN:'Workspacename must be at least 4 characters',
    WORKSPACENAME_CHECK_ERR:'Error checking workspacename',
    WORKSPACENAME:'Please enter your workspace name!',
    WORKSPACENAME_NOT_FOUND_ERR:'Workspace name not found in URL or localStorage',
    WORKSPACE_FETCH_ERR:'Error fetching workspaces:',
    WORKSPACENAME_EMPTY_ERR:'Workspace name cannot be empty!',
    WORKSPACENAME_UPDATE_SUCC:'Workspacename updated successfully!',
    WORKSPACENAME_UPDATE_ERR:'Error updating workspacename.',
    LOGO_UPLOAD:'Please upload a new logo!',
    WORKSPACELOGO_UPDATE_SUCC:'Workspace logo updated successfully!',
    WORKSPACELOGO_UPDATE_ERR:'Error updating workspace logo.',
    WORKSPACE_CREATE_SUCC:'Workspace created successfully!',
    WORKSPACE_CREATE_ERR:'Something went wrong!',
    WORKSPACE_DELETE_SUCC:'Workspace deleted successfully!',
    WORKSPACE_DELETE_ERR:'Error deleting workspace:',
    ERR_MSG:"Error",
    SUCC_MSG:"Success",
    DEL_MSG:"Deleted",
    WORSKPACENAME_ALREADY_EXISTS:"Workspace name already exists. Choose a different name.",

  };

  export const StreamMessages = {
    STREAM_FETCH_ERR:'Failed to fetch streams!',
    SUBSTREAM_FETCH_ERR:'Failed to fetch sub-streams!',
    STREAM_CREATE_SUCC:'Stream created successfully!',
    SUBSTREAM_DELETE_SUCC:'Sub-stream deleted successfully!',
    SUBSTREAM_DELETE_ERR:'Failed to delete sub-stream!',
    STREAM_DELETE_SUCC:'Stream deleted successfully!',
    STREAM_DELETE_ERR:'Failed to delete stream!',
    SUBSTREAM_ADD_SUCC:'The sub stream has been successfully added.',
    SUBSTREAM_ADD_ERR:'Failed to create sub stream',
    SUBSTREAM_ADD_MSG:'Sub Stream Added',
    SUBSTREAM_ERR_MSG:'Error',
    ERR_MSG:'Error',
    SUCC_MSG:'Success',
    DEL_MSG:'Deleted',
    STREAM_UPDATE_FAIL_MSG:'Failed to update stream.',
    SUB_STREAM_UPDATE_FAIL_MSG:'Failed to update sub-stream.',
    SUBSTREAM_FETCH_ERR_MSG:'Error fetching substreams:',
    STREAM_UPDATE_SUCC:'Stream updated successfully!',
    SUBSTREAM_UPDATE_SUCC:'Sub-stream updated successfully!',
  };

  export const TeamMessages = {
    TEAM_FETCH_ERR:'Failed to fetch teams!',
    TEAM_STREAM_FETCH_ERR_MSG:'Error fetching streams:',
    TEAM_ERR_MSG:'Error',
    TEAM_SUCC_MSG:'Success',
    TEAM_NOT_FOUND:'Team not found!',
    TEAM_DETAILS_FETCH_ERR:'Failed to fetch team details!',
    TEAM_CREATE_SUCC:'Team created successfully!',
    TEAM_CREATE_ERR:'Failed to create team!',
    TEAM_UPDATE_SUCC:'Team updated successfully!',
    TEAM_UPDATE_ERR:'Failed to update team!',
    TEAM_DELETE_MSG:'Deleted',
    TEAM_DELETE_SUCC:'Team deleted successfully!',
    TEAM_DELETE_ERR:'Error deleting team:',
    TEAM_TITLE:'Please enter team title!',
    TEAM_DESCRIPTION:'Please enter team descritpion!',
  };

  export const UserMessages = {
    USER_FETCH_FAIL:'Failed to fetch users.',
    USER_FETCHING_ERR:'Error Fetching Users',
    USER_ADD_SUCC:'User added successfully!',
    SUBASSIGNED_USER_FETCH_ERR:'Failed to fetch subAssigned users.',
    USER_REMOVE_SUCC:'User removed successfully!',
    USER_REMOVE_ERR:'Failed to remove user.',
    USER_ADD_ERR:'Failed to add user.',
    USER_ERR:'User already added or not selected.',
    PROVIDE_ALL_FIELDS:'Please provide all required fields',
    ID_ERR:'ID Not Found!',
    USERDATA_PARSE_ERR:'Error parsing user data:',
    USERDATA_UPDATED_SUCC:'User details updated successfully!',
    USERDATA_UPDATED_ERR:'Error updating user details.',
    USER_TEAM_FETCH_ERR:'Error fetching teams:',
    USER_TEAM_FETCH_ERR_MSG:'Failed to fetch teams.',
    USER_BRANCH_FETCH_FAIL:"Failed to load branches.",
    USER_ERR_MSG:'Error',
    USER_SUCC_MSG:'Success',
    USER_CREATE_SUCC_MSG:'User Created',
    USER_CREATE_SUCC:'The user has been successfully added.',
    USER_CREATE_ERR:'Failed to create user',
    USER_USERNAME_REQ:'Username is required',
    USER_USERNAME_LIMIT:'Username must be at least 3 characters',
    USER_USERNAME_CHECK_ERR:'Error checking username',
    USER_EMAIL_REQ:'Email is required',
    USER_EMAIL_CHECK_ERR:'Error checking email',
    USER_REQ_MSG:'Required',
    USER_FNAME_REQ:"Firstname is required",
    USER_LNAME_REQ:"Lastname is required",
    USER_FNAME_MIN_LIMIT:'Firstname should be minimum of 3 characters',
    USER_LNAME_MIN_LIMIT:'Lastname should be minimum of 3 characters',
    USER_USERNAME_MAX_LIMIT:'Username should not exceed 10 characters',
    USER_USERNAME_PATTERN:'Only letters, numbers, or underscores allowed',
    VALID_USER_EMAIL_REQ:'Valid email required',
    USER_PASS_REQ:'Password is required',
    USER_PASS_MIN_LIMIT:'Password must be at least 8 characters',
    USER_PASS_PATTERN:'Password must have uppercase, lowercase, and a number',
    USER_CONFIRM_PASS:'Confirm your password',
    USER_PASS_MATCH_ERR:'Passwords do not match!',
    USER_TEAM_REQ:'Team name required',
    USER_ROLE_SELECT:'Select a role',
    USER_BRANCH_SELECT:'Select a  branch',
    USER_STATUS_SELECT:'Select a status',
    USER_WORKSPACE_FETCH_ERR:'Error fetching workspace:',
    USER_DELETE_SUCC_DESCR:'User deleted successfully',
    USER_STATUS_SUCC_DESCR:'User status updated successfully',
    USER_TEAM_TITLE_SUCC_DESCR:'User assigned to different team successfully.',
    FETCH_USERS_ERR:"Error fetching users",
    FAILED_TO_SEND_EMAILS:"Failed to resend reset emails",
    IMPORT_USERS_ERR:"Error importing users",
    USER_IMPORT_SUCC:"Users imported successfully!",
    WORKSPACENAME_MISSING:"Workspace name is missing!",
    SELECT_FILE_TO_UPLOAD:"Please select a file to upload!",
    FILE_EXTENSION_ALLOWED:"Only .xls or .xlsx files are allowed.",
    INVALID_FILE_TYPE:"Invalid File Type",
    USER_UPDATED_SUCC:"User updated successfully!",
    USER_UPDATE_ERR:"Error updating user",
    PLEASE_SELECT_WORKSPACE:'Please select a workspace!',
    USER_TRANSFERRED_SUCC:"Users transferred successfully!",
    USER_REPLICATED_SUCC:"Users replicated successfully!",
    NO_USERS_AVAILABLE_TO_EXPORT:"No users available for export!",
    NO_VALID_USERSPTO_EXPORT:"No valid users available for export!",
    USER_EXPORT_SUCC:"Users exported successfully!",
  };

  export const CreateActionMessages = {
    ACTION_TITLE_REQ:"Please Input Action Title!",
    NOTES_REQ:"Please input the action task description!",
    WORKSPACENAME_REQ:"Workspacename is required!",
    SELECTEDUSER_REQ:"Please select user to assign the task!",
    PRIORITY_REQ:"Please the priority!",
    EXPECTED_COMPLETION_DATE_REQ:"Please select the expected completion date of action assigned!",
  };

  export const ActionMessages = {
    ACTION_CREATE_SUCCESS:'Action created successfully!',   
    ACTION_CREATE_ERR:'Error creating action.',
    AUTHORIZED_ERR:'You are not authorized to change the field.',
    ACTION_FETCH_ERR:'Error Fetching Actions.',
    STATUS_UPDATED_SUCC:'Status updated successfully!',
    STATUS_UPDATED_ERR:'Error updating status',
    DESCRIPTION_UPDATE_WARN:'You can only update the description of the selected action.',
    DESCRIPTION_UPDATE_SUCC:'Description updated successfully!',
    DESCRIPTION_UPDATE_ERR:'Error updating description',
    LOGIN_TO_VIEW:"Please log in to view this action.",
    ACTION_NOT_FOUND:"Action not found.",
};

export const ImportMessages = {
  IMPORT_FAILED:"Import Failed",
  PRODUCTS_IMPORTED_SUCC:"Products imported successfully!",
  SELECT_FILE_TO_UPLOAD:"Please select a file to upload.",
  INVALID_FILE_TYPE:"Invalid file type",
};


  export const CommentMessages = {
    COMMENT_FETCH_ERR:'Error fetching comments:',
    COMMENT_LOAD_ERR:'Failed to load comments.',
    USER_MENTION_ERR:'Error fetching mention user:',
    COMMENT_ADD_ERR:'Failed to add comment.',
    COMMENT_ADD_SUCC:'Comment added successfully.',
    REPLY_ADD_ERR:'Failed to add reply.',
    REPLY_ADD_SUCC:'Reply added successfully.',
  };

  export const HistoryMessages = {
    HISTORY_FETCH_ERR:'Error fetching history:',
  };


  export const ValidationMessages = {
    ACCESSORIES_TYPE_REQ:"Accessories type is required",
    ACCESSORY_NAME_LIM:"Accessories Name must be at least 3 characters",
    ACCESSORY_NAME_REQ:"Accessories Name is required",
    SERIAL_NUMBER_PATTERN:"Serial Number can only contain letters, numbers, and dashes",
    SERIAL_NUMBER_REQ:"Serial Number is required",
    INV_DATE_FORMAT:"Invalid date format",
    DATE_OF_PURCHASE_REQ:"Date of Purchase is required",
    WARRANTY_PERIOD_FORMAT:"Warranty Period must be a number",
    WARRANTY_PERIOD_MIN:"Warranty Period must be greater than zero",
    WARRANTY_PERIOD_REQ:"Warranty Period is required",
    BRANCH_REQ:"Branch is required",
    SYSTEMBRAND_REQ:"System Brand is required",
    SYSTEMMODEL_REQ:"System Model is required",
    SYSTEMNAME_REQ:"System Name is required",
    OS_REQ:"Operating System is required",
    CPU_REQ:"CPU is required",
    RAM_PATTERN:"RAM must be a number followed by GB/MB/TB (e.g., 16GB)",
    RAM_REQ:"RAM is required",
    STORAGETYPE_REQ:"Storage Type is required",
    STORAGE_CAPACITY_FORMAT:"Storage Capacity must be a number followed by GB/TB (e.g., 512GB, 1TB)",
    STORAGE_CAPACITY_REQ:"Storage Capacity is required",
    INV_MAC_ADDRESS:"Invalid MAC Address format (e.g., 00:1A:2B:3C:4D:5E)",
    MAC_ADDRESS_REQ:"MAC Address is required",
    INV_IP_ADDRESS:"Invalid IP Address format (e.g., 192.168.1.1)",
    IP_ADDRESS_REQ:"IP Address is required",
    PRODUCT_KET_FORMAT:"Product Key must be alphanumeric with optional hyphens (e.g., ABCD-1234-EFGH)",
    PRODUCT_KEY_REQ:"Product Key is required",
    WARRANTY_PERIOD_PATTERN:"Warranty Period must be a number followed by 'months' or 'years' (e.g., 12months, 2years)",
    DATE_OF_PURCHASE_MAX:"Date of Purchase cannot be in the future",
  };

  export const DeviceFormMessages = {
    ACCESSORIES_ADD_SUCC:"Accessory added successfully!",
    ADDING_ERR:"Error adding accessory",
    SYSTEM_ADD_SUCC:"System added successfully!",
    SYSTEM_ADD_ERR:"Error adding system",
    SELECT_VALID_USER:"Please select a valid user.",
    ASSIGN_SUCC:"Assignment successful!",
    FAILED_FETCH_PRODUCT:"Failed to fetch product details",
    PRODUCT_UPDATE_SUCC:"Product updated successfully",
    FAILED_UPDATE_PRODUCT:"Failed to update product",
    FAILED_LOAD_BRANCHED:"Failed to load branches.",
  };


  export const FeedMessages = {
    ORGANIZATION_FEED_ERR:"Error fetching feed data:",
    ORGANIZATION_FEED_ERR_MSG:"Something went wrong while fetching data",
    TEAM_FEED_FETCH_TEAMS_WARN:"No teams found for user.",
    TEAM_FEED_ERR:"Error fetching team feed:",
    TEAM_FEED_ERR_MSG:"Failed to load team feed.",
    POST_FEED_CONTENT_WARN:"Post content cannot be empty",
    POST_SELECT_TEAM_WARN:"Please select a team.",
    POST_CREATE_SUCC:"Post created successfully!",
    POST_CREATE_FAIL:"Failed to create post",
  };

  export const eventMessages = {
    SERVER_ERR_FETCH:"Server error fetching events",
    INVALID_ID:"Invalid IDs provided",
    EVENT_NOT_FOUND:"Event not found",
    SESSION_NOT_FOUND:"Session not found in event",
    SERVER_ERR_TOGGLE:"Server error toggling attendance",
    EVENT_CREATE:"Event Created successfully.",
    EVENT_CANCELLED: "Event Cancelled Successfully",
    FAILED_TO_CANCEL_EVENT:"Failed to cancel event",
    FAILED_TO_CREATE_EVENT:"Error Creating Event",
    FAILED_FETCH_ATTENDED_EVENT:'Error fetching attended events',
    USER_ID_MISSING: "User ID missing in request",
    ATTENDANCE_UPDATED_SUCCESSFULLY:"Attendance Updated Successfully",
    FAILED_TO_UPDATE_ATTENDANCE:"Failed To Update Attendance",
    DATE_SESSION_REQUIRED: "Date and sessions are required",
    ERROR_FETCHING_ASSIGNED_EVENTS:"Error fetching assigned events",
    INTERNAL_SERVER_ERROR:"Internal Server Error",
    INVALID_PAYLOAD:"Invalid payload",
    ERROR_IN_MARKATTENDANCE:"Error in markAttendance",
    ERROR_CANCELLING_EVENT:"Error cancelling event",
    FAILED_TO_MARKATTENDANCE:"Failed to mark attendance",
  };

